# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d8f01050c9cd511a0cf50b44a254c517add003cae4326e72d1941580df2536b60ae22cff8bab89f53b197d10c7e14af452f2e55af6a05865976eeaca0f547b4

test:
  secret_key_base: 19f32ecfb131c7eacd26fc8489079f8fd0e6af4c54c485bdde7db1f90c2474f05f995c7a4f5efada16e8f172be2545cac8fda61de8e4738a334daafa7973768b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
